; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: %riscv64_cheri_purecap_opt -S -o - -passes=loop-reduce %s | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n64-S128-A200-P200-G200"
target triple = "riscv64-unknown-freebsd"

define i32 @foo(i64 %x, i64 %y, i64 %z, i64 %u, i64 %v, i64 %end) {
; CHECK-LABEL: define i32 @foo
; CHECK-SAME: (i64 [[X:%.*]], i64 [[Y:%.*]], i64 [[Z:%.*]], i64 [[U:%.*]], i64 [[V:%.*]], i64 [[END:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CALL:%.*]] = call ptr addrspace(200) @bar()
; CHECK-NEXT:    [[TMP0:%.*]] = sub i64 0, [[END]]
; CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[X]], -8
; CHECK-NEXT:    [[TMP2:%.*]] = shl i64 [[Z]], 3
; CHECK-NEXT:    br label [[PREHEADER:%.*]]
; CHECK:       preheader:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[ADD:%.*]], [[COND:%.*]] ], [ [[Y]], [[ENTRY:%.*]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[TMP0]], [[I]]
; CHECK-NEXT:    [[TMP4:%.*]] = shl i64 [[I]], 3
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 [[TMP1]], [[TMP4]]
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr addrspace(200) [[CALL]], i64 [[TMP5]]
; CHECK-NEXT:    br label [[FOR:%.*]]
; CHECK:       cond:
; CHECK-NEXT:    [[ADD]] = add nsw i64 [[U]], [[V]]
; CHECK-NEXT:    br label [[PREHEADER]]
; CHECK:       for:
; CHECK-NEXT:    [[LSR_IV1:%.*]] = phi ptr addrspace(200) [ [[SCEVGEP2:%.*]], [[FOR]] ], [ [[SCEVGEP]], [[PREHEADER]] ]
; CHECK-NEXT:    [[LSR_IV:%.*]] = phi i64 [ [[LSR_IV_NEXT:%.*]], [[FOR]] ], [ [[TMP3]], [[PREHEADER]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = load double, ptr addrspace(200) [[LSR_IV1]], align 8
; CHECK-NEXT:    [[LSR_IV_NEXT]] = add i64 [[LSR_IV]], [[Z]]
; CHECK-NEXT:    [[SCEVGEP2]] = getelementptr i8, ptr addrspace(200) [[LSR_IV1]], i64 [[TMP2]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[LSR_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[CMP]], label [[COND]], label [[FOR]]
;
entry:
  %call = call ptr addrspace(200) @bar()
  br label %preheader

preheader:
  %i = phi i64 [ %add, %cond ], [ %y, %entry ]
  br label %for

cond:
  %add = add nsw i64 %u, %v
  br label %preheader

for:
  %iv = phi i64 [ %iv.next, %for ], [ %i, %preheader ]
  %0 = sub nsw i64 %iv, %x
  %arrayidx = getelementptr inbounds double, ptr addrspace(200) %call, i64 %0
  %1 = load double, ptr addrspace(200) %arrayidx, align 8
  %iv.next = add i64 %iv, %z
  %cmp = icmp eq i64 %iv.next, %end
  br i1 %cmp, label %cond, label %for
}

declare ptr addrspace(200) @bar() addrspace(200)
